name: "CI: meson: gcc 9"

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ubuntu:20.04

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        # Prevent blocking apt install on a question during configuring of tzdata.
        export ENV DEBIAN_FRONTEND=noninteractive
        apt update
        apt install mm-common g++-9 meson ninja-build python3-setuptools --yes
        export CXX=g++-9
        meson -Dwarnings=fatal _build
        cd _build
        # Meson from 0.54.0 understands "meson compile".
        # Ubuntu 20.04 uses meson 0.53.2.
        ninja
    - name: Test
      run: |
        cd _build
        meson test
    - name: Dist
      run: |
        apt install git --yes
        # dist runs setup again so we need to specify CXX again.
        export CXX=g++-9
        cd _build
        meson dist
