name: "CI: zig build"

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        targets:
          - x86_64-linux-gnu
          - x86_64-linux-musl
          - x86-linux-gnu
          - x86-linux-musl
          - aarch64-linux-gnu
          - aarch64-linux-musl
          - riscv64-linux-musl
          - mipsel-linux-musl
          - mips-linux-musl
          - powerpc64-linux-musl
          - x86_64-macos
          - aarch64-macos
          - x86_64-windows
          - x86-windows
          - aarch64-windows

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - name: Build Summary ${{ matrix.targets }}
        run: zig build -DTests --summary all -freference-trace -Dtarget=${{ matrix.targets }}